<? if (isset($this->error_message)): ?><p style="color: #cd0a0a"><?= $this->error_message ?></p><? endif; ?>
<div align="center" style="font-size: 200%">
    <form action="/index/parent_control" method="post">
        <table>
            <tr>
                <td>Set Question size:<input type="text" name="question_size"/></td>
                <td><input type="radio" name="op_type" value="question_size" checked="checked"></td>
            </tr>
            <tr>
                <td>Pause</td>
                <td><input type="radio" name="op_type" value="pause" ></td>
            </tr>
            <tr>
                <td>Password: <input type="password" name="password" autocomplete="off" /></td>
                <td>
                    <button type="submit">Submit</button>
                </td>
            </tr>
        </table>
    </form>
</div>