<div align="center" style="font-size: 300%">
    <p>
        Done
    </p>

    <p>
        Gave <?= $this->give_size ?> questions
    </p>

    <p>
        You did <?= $this->real_size ?> questions
    </p>

    <p>
        Total wrong <?= $this->wrong_size ?> times
    </p>

    <p>
        Total you save time: <?= $this->total_rest_second ?> seconds!!!!
    </p>
   <p>
        Your reward video time: <?= $this->video_minutes ?> minutes!!!!
    </p>

    <p>
        <a href="/index">Go back Main Page</a>
    </p>


</div>