<script type="text/javascript">
    $(document).ready(function () {
        setInterval(mTimer, 1000);
        document.getElementById("result").focus();
    });

    var start =<?= $this->timeout_time?>;

    function mTimer() {
        $("#restSeconds").text(start);
        start = start - 1;
        if (start < 20) {
            $("#restSeconds").css('color', 'red');
        }
        if (start < 0) {
            window.location.href = "/random_add/timeout"
        }
    }
</script>
<div align="center" style="font-size: 300%">
    <? if (isset($this->error_message)): ?><p style="color: #cd0a0a"><?= $this->error_message ?></p><? endif; ?>
    <p>
        You have <label><?= $this->rest ?></label> Questions
    </p>
    <p>
        You have <label id="restSeconds"><?= $this->timeout_time ?></label> seconds
    </p>
    <br/>

    <form action="/random_add/answer" method="post">
        <input type="hidden" name="v1" value="<?= $this->v1 ?>">
        <input type="hidden" name="v2" value="<?= $this->v2 ?>">
        <input type="hidden" name="op" value="<?= $this->op ?>">
        <?= $this->v1 ?><?= $this->op ?><?= $this->v2 ?> = <input type="text" id="result" name="result" autocomplete="off">
        </p>
        <input type="submit">
    </form>

    <hr/>
    <div>
        <p>You have <?= $this->rest_time?> seconds rest time</p>
        <p><a href="/random_add/rest">I want have a rest !</a></p>
    </div>
</div>

